font_size 12
confirm_os_window_close 0

map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

# Config reload
map ctrl+shift+f5 load_config_file

# Scrolling
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down

map ctrl+shift+page_up scroll_page_up
map ctrl+shift+page_down scroll_page_down

map ctrl+shift+home scroll_home
map ctrl+shift+end  scroll_end

scrollback_lines 10000

# Theme
include current-theme.conf
font_family      monospace

