#!/usr/bin/env bash

function try { "$@" || sleep 0; }

function prevent_sudo_or_root(){
  case $(whoami) in
    root)echo -e "\e[31m[$0]: This script is NOT to be executed with sudo or as root. Aborting...\e[0m";exit 1;;
  esac
}